version: "3.0"

services:
  trace-source-test:
    image: "trace:${TAG:-1.0.0}"
    build:
      context: ./ 
      dockerfile: Dockerfile
    restart: always
    container_name: "trace_std_test"
    volumes:
      - /etc/localtime:/etc/localtime:ro # 设置容器时区与宿主机保持一致
      - /data_loader/trace_test/logs:/usr/src/app/trace/logs
      - /data_loader/trace_test/data_loader:/usr/src/app/trace/data_loader
      - /data_loader/trace_test/resource:/usr/src/app/trace/resource
    ports:
      - 18076:18075
    environment:
      TZ: "Asia/Shanghai"